### ISSUE TITLE
How to run ?as for python  version is 3.6

### ISSUE THREAD

**Issue by xiaoyuge16** [QData/deepWordBug#1]
How to run ?as for python  version is 3.6

**Comment by gaoji7777** [comment]
The code is written in Python 2.7. There might be issues to direct use it on python 3. I've put this info into our readme. Thank you!

**Comment by xiaoyuge16** [comment]
When I install pytorch on windows with python 2.7, I find pytorch website show that "PyTorch does not support Python 2.7 on Windows. Please install with Python 3."
Can I run deepwordbug with python3 by change all the print ".......something....." to all the print(".........something.......")？
Anything else need to change？

**Comment by gaoji7777** [comment]
You can try to migrate the code to python 3 using some guide, for example, "http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html". In addition to print, xrange and integer division are quite different and might cause problems.

**Comment by xiaoyuge16** [comment]
ok,3Q

**Comment by xiaoyuge16** [comment]
I use a Linux virtual machine to run, when I run it , It tells me that I don't have a cuda, what should I do? Thanks~

**Comment by xiaoyuge16** [comment]
![default](https://user-images.githubusercontent.com/23721563/42725849-729c251a-87bd-11e8-93a4-ea6eaf818ad4.PNG)
what should I do?
I am a beginner, so my question maybe very simple.

**Comment by gaoji7777** [comment]
It's just a warning so you can ignore it for now. For the cuda, you need to install cuda from nvidia to use GPU for deep learning.
