### ISSUE TITLE
Error when running attack.py

### ISSUE THREAD

**Issue by alianoroozi** [QData/deepWordBug#5]
Hi, I am trying to build a model and create adversaries. I used "python2 train.py --data 3 --model bilstm" to build a model and save it. Then, I used "python2 attack.py --data 3 --model bilstm --modelpath models/bilstm_3_checkpoint.dat" for adversary generation.  But the latter command gave the following error:
RuntimeError: expand(torch.cuda.FloatTensor{[128, 1]}, size=[128]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
![screenshot](https://user-images.githubusercontent.com/20418558/46264317-1c5ab000-c524-11e8-9956-ac714928a48c.png)

Do you have any idea why this error is given? 
By the way, I tried pytorch=0.4.1 and 0.4.0, but both versions of pytorch failed.

**Comment by gaoji7777** [comment]
Our code is using Pytorch 0.3.0(See our README for more dependencies), which has known incompatible problems with 0.4.0. We are in the process of updating the code to Pytorch 0.4. You can try to run the code with Pytorch 0.3.0. Thank you!

**Comment by alianoroozi** [comment]
> Our code is using Pytorch 0.3.0(See our README for more dependencies), which has known incompatible problems with 0.4.0. We are in the process of updating the code to Pytorch 0.4. You can try to run the code with Pytorch 0.3.0. Thank you!

OK, thanks.

**Comment by alianoroozi** [comment]
I ran train.py and then attack.py to generate adversarial examples for data 3 (DBPedia). Now, I have 'dict/' and 'advsamples/' folders. Could you please explain me how I can get misspelled words for this data? 

I am doing research on your paper and I want to correct the misspelled words and then measure the accuracy of the model.

**Comment by gaoji7777** [comment]
All the information is stored in the generated data file in advsamples/ folder. You can load it with
dat = torch.load(advsamplefilename)
dat will then be a dictionary, with
'wordinput' -- a list of adversarial sequences in the tokenized form,
and 'advinputs' -- a pytorch tensor stores the adversarial sequences in the form of dictionary indexs.
It also includes original sample (in the form of dictionary indexs) and original label

**Comment by alianoroozi** [comment]
thanks

**Comment by alianoroozi** [comment]
Hi again,
Data set 3 (dbpedia) has 560000 train samples and 70000 test samples. In attack.py, it seems all the test samples are loaded, but only 2560 samples are modified by attackword() method. How are these samples selected? Where does subsampling happen?

**Comment by gaoji7777** [comment]
> Hi again,
> Data set 3 (dbpedia) has 560000 train samples and 70000 test samples. In attack.py, it seems all the test samples are loaded, but only 2560 samples are modified by attackword() method. How are these samples selected? Where does subsampling happen?

Thank you for asking the question. There is a parameter controlling how many adversarial samples generated in the process. We have added the following description into README.

--maxbatches [batches=20] # Number of batches of adversarial samples generated, samples are selected randomly. Since some test dataset is very large, to evaluate the performance we add this parameter to generate on parts of data. By default it will generate 2560 samples.

**Comment by alianoroozi** [comment]
Thank you.
